### ISSUE TITLE
Broken Tiling

### ISSUE THREAD

**Issue by JSterling8** [artemsheludko/bef#11]
Intermittent issues with tiling. When there are a certain amount of posts, this happens:

![image](https://user-images.githubusercontent.com/2670096/34932037-47bc455a-f9c9-11e7-908c-8406024ed68d.png)

In the image above, there were 17 posts, with 12 posts per page. I'm having a hard time figuring out why it occasionally does this.

**Comment by artemsheludko** [comment]
@JSterling8 Perhaps this problem only appears on the local server? Have you tried to place the site on Github Pages?

**Comment by JSterling8** [comment]
https://popatato.com/

**Comment by JSterling8** [comment]
Happens on Chrome and Firefox. Ubuntu and Windows.

![image](https://user-images.githubusercontent.com/2670096/34934938-19056902-f9d4-11e7-9847-9372d0701098.png)

**Comment by artemsheludko** [comment]
Did you change the value in Paginate? If so, try changing to 12. Does this happen with the default values?
![screen shot 2018-01-15 at 11 38 17 am](https://user-images.githubusercontent.com/22279513/34936470-339a3fb6-f9ea-11e7-8753-cc1be35f3a34.png)

**Comment by JSterling8** [comment]
I've tried with 12 and 9. Happens with both.

**Comment by JSterling8** [comment]
Can you reproduce if you clone and do `jekyll serve`? https://github.com/popapompom/popapompom.github.io

**Comment by artemsheludko** [comment]
@JSterling8 Bug with Broken Tiling fixed. Try it now, everything should work.

![screen shot 2018-01-15 at 4 35 47 pm](https://user-images.githubusercontent.com/22279513/34948349-86a1d3b0-fa15-11e7-8c62-e1785ac8f61c.png)

**Comment by JSterling8** [comment]
Awesome - works now. Thanks a million!

**Comment by artemsheludko** [comment]
@JSterling8 You are welcome! Enjoy the journey 😄  👍
